// <auto-generated />
using System;
using Calculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calculator.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    partial class CalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Calculator.Models.CalculationLog", b =>
                {
                    b.Property<int>("CalculationLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("FirstOperand")
                        .HasColumnType("decimal(20, 10)");

                    b.Property<string>("Operator")
                        .HasMaxLength(100);

                    b.Property<decimal?>("Result")
                        .HasColumnType("decimal(20, 10)");

                    b.Property<decimal>("SecondOperand")
                        .HasColumnType("decimal(20, 10)");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("CalculationLogId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
